### ISSUE TITLE
Ensure configuration files align with current standards in the main PatternFly repos / previous package within PF-React

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/react-catalog-view#29]
- [x] Check that dependencies have proper semver characters
- [x] Check that installing dependencies does not cause any warnings
- [x] Check that dependencies are properly sorted into deps/devDeps/peerDeps
- [ ] #33
- [x] Check that linting does not cause any errors/warnings to be thrown
- [x] Check that tsconfig matches configuration as it existed in the pre-extraction package
- [x] Check that running a build does not cause any errors/warnings
